package parse

import (
	"fmt"
	"iter"
	"strings"
)

// Composite contains a namespace identifier whose evaluated environment can be
// inherited in the definition of a [namespace].
//
// A Composite can optionally specify an in-line [parameter] list that is
// appended to that [namespace]'s own parameter list definition.
type Composite struct {
	Ident      string
	Parameters []Parameter
}

// Argument is an actual [Parameter] value passed to the [Namespace] being
// composited.
// type Argument Parameter

func (c Composite) String() string {
	if c.Ident == "" {
		return ""
	}

	var par string

	if len(c.Parameters) > 0 {
		pars := make([]string, len(c.Parameters))
		for i, p := range c.Parameters {
			pars[i] = fmt.Sprintf(`%v`, p.Value)
		}

		par = strings.Join(pars, FS)
	}

	return fmt.Sprintf(`%s%s%s%s`, c.Ident, po, par, pc)
}

// Arguments returns a [Parameter.Value] sequence of all [Composite.Parameter]s.
//
// These parameters are specified in-line in the [Composite] list of a
// [Namespace] definition, which get appended to the composited
// [Namespace.Parameters], but only for that evaluated instance.
// For example:
//
//	foo(1) { x = _; }
//	bar<foo>
//	baz<foo(2)>
//
// The environment generated by "foo" or "bar" will export x=1,
// but "baz" will export x=2.
func (c Composite) Arguments() iter.Seq[any] {
	return func(yield func(any) bool) {
		for _, p := range c.Parameters {
			if !yield(p.Value) {
				return
			}
		}
	}
}
